default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production: &production
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

training:
  <<: *production

development:
  <<: *default
  host: desafiodev-postgres
  database: desafiodev_development
  min_messages: warning
  username: postgres
  password: postgres

test:
  <<: *default
  host: desafiodev-postgres
  database: desafiodev_test
  min_messages: warning
  username: postgres
  password: postgres
